### ISSUE TITLE
Update Strapi Connection & Structure

### ISSUE THREAD

**Issue by IanSaucy** [BU-Spark/se-d7-dashboard#84]
Update Strapi and the requests to strapi to satisfy the following:

```[tasklist]
### Tasks
- [ ] https://github.com/BU-Spark/se-d7-dashboard/issues/85
- [ ] Make resources easily editable(they use JSON right now) on Strapi
- [ ] Update fronted to support new Strapi structure
```
