### ISSUE TITLE
Fall 2023 - Final Stretch

### ISSUE THREAD

**Issue by IanSaucy** [BU-Spark/se-d7-dashboard#86]
These are the tasks that we need to accomplish to wrap-up for FA 23 

```[tasklist]
### Tasks
- [x] https://github.com/BU-Spark/se-d7-dashboard/issues/91
- [x] https://github.com/BU-Spark/se-d7-dashboard/issues/92
- [x] https://github.com/BU-Spark/se-d7-dashboard/issues/93
- [ ] https://github.com/BU-Spark/se-d7-dashboard/issues/87
- [x] https://github.com/BU-Spark/se-d7-dashboard/issues/94
- [x] Return Events and Calendar items in descending order from Strapi
- [x] https://github.com/BU-Spark/se-d7-dashboard/issues/95
- [ ] https://github.com/BU-Spark/se-d7-dashboard/issues/88
- [ ] Comprehensive review of application. Find as many bugs as possible
- [ ] Add all require PWA assets and files
- [x] https://github.com/BU-Spark/se-d7-dashboard/issues/96
- [ ] https://github.com/BU-Spark/se-d7-dashboard/issues/98
- [ ] https://github.com/BU-Spark/se-d7-dashboard/issues/97
- [x] Show 'submit request' button only when user logged in
- [ ] https://github.com/BU-Spark/se-d7-dashboard/issues/99
```
